force-app/main/default/objects/Email_Service_Message__c/Email_Service_Message__c.object-meta.xml
<CustomObject>
    <label>Email Service Message</label>
    <nameField>
        <displayFormat>{00000000}</displayFormat>
        <label>Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Email Service Messages</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Email_Service_Message__c/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>32768</length>
    <type>Html</type>
</CustomField>

force-app/main/default/objects/Email_Service_Message__c/fields/Recipients__c.field-meta.xml
<CustomField>
    <fullName>Recipients__c</fullName>
    <label>Recipients</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/EmailServiceHandler.cls
global class EmailServiceHandler implements Messaging.InboundEmailHandler {

    global Messaging.InboundEmailResult handleInboundEmail(Messaging.InboundEmail email, Messaging.InboundEnvelope envelope) {

        Messaging.InboundEmailResult result = new Messaging.InboundEmailresult();

        Email_Service_Message__c messageRecord = new Email_Service_Message__c();

            messageRecord.Subject__c    = email.subject;
            messageRecord.Sender__c     = email.fromAddress;
            messageRecord.Recipients__c = string.join(email.toAddresses,',');
            messageRecord.Body__c       = email.htmlBody;

        insert messageRecord;

        if (email.binaryAttachments != null) {
            
            for (Messaging.InboundEmail.BinaryAttachment bAttachment : email.binaryAttachments) {
                
                Attachment attachment = new Attachment();
                attachment.Name = bAttachment.fileName;
                attachment.Body = bAttachment.body;
                attachment.ParentId = messageRecord.Id;
                insert attachment;

            }

        }
    
        return result;
    }
}